### ISSUE TITLE
Test suite build failure

### ISSUE THREAD

**Issue by bergmark** [kawu/dawg-ord#2] opened 2016-01-12 14:07 UTC
From the stackage nightly build, I'll constrain dawg-ord to < 0.5 until this is fixed.

```
 Preprocessing test suite 'test' for dawg-ord-0.5.0.0...

tests/test.hs:3:18:
    Could not find module ‘Ord’
    Use -v to see a list of the files searched for.
```

**Comment by kawu** [comment] 2016-01-12 14:27
Hmm, strange that Travis didn't catch it, and I don't get this behavior on my local machine either.

Maybe the problem is that the `Ord` module was lacking from the `other-modules` section of the `test-suite`?  I've just committed the fix (1c6aea879e45988533d351acf29229df7cba2131) and I'm going to upload the new version to Hackage soon.

**Comment by bergmark** [comment] 2016-01-12 14:47
Yes if a module is missing from exposed/other-modules it won't be packed into the tarball. You can test this by installing from the tarball instead of the root of the repository.

**Comment by kawu** [comment] 2016-01-12 15:00
Thanks for explanations, you are absolutely right; I've just verified that the newest version on Hackage compiles fine with tests enabled.

**Closed as completed by kawu** 2016-01-12 15:00 UTC
